// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxL3W6JJa-Gwh0xIz9Ey_9-t6rPgUM054',
    appId: '1:749098500441:web:46bfc8a0c19140b1408c48',
    messagingSenderId: '749098500441',
    projectId: 'attendancescanner-a5bf4',
    authDomain: 'attendancescanner-a5bf4.firebaseapp.com',
    storageBucket: 'attendancescanner-a5bf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQb6WlpzZy5xTqEnfevN-ZuAjdtUi_pQM',
    appId: '1:749098500441:android:657882c8fd79333e408c48',
    messagingSenderId: '749098500441',
    projectId: 'attendancescanner-a5bf4',
    storageBucket: 'attendancescanner-a5bf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEslzQVWCDBbrbbHY3W6fTlnxBfAN7I2Q',
    appId: '1:749098500441:ios:31adfd44f555cd78408c48',
    messagingSenderId: '749098500441',
    projectId: 'attendancescanner-a5bf4',
    storageBucket: 'attendancescanner-a5bf4.firebasestorage.app',
    iosBundleId: 'com.example.attendanceScanner',
  );
}
